### ISSUE TITLE
Create status check for Dug

### ISSUE THREAD

**Issue by cschreep** [helxplatform/dug#122]
Dug relies on several other backend services (e.g. elastic, redis). We can't crawl or search without them, which means we can't start up Dug on kubernetes until those other services come online. Right now we check it directly with some scripted curl calls, but it would be an improvement if we could just ask Dug itself if it was in a runnable state. 

Acceptance criteria: 
 * [ ] add a CLI integration so that a user can call `dug status` and receive some meaningful output.
    * [ ] if everything is OK, exit with exit code 0. Otherwise exit with exit code 1.
    * [ ] CLI output should look something like.:
    ```shell
    $ dug status
       - elasticsearch (elastic.svc:9200) ...ok
       - redis (redis.svc:6379) ...ok
       - ...
    ```

* [ ] add a REST API endpoint, e.g. /health, /_health, etc.
  * [ ] Should return HTTP 200 if everything is OK, HTTP 500 if something is down
  * [ ] Response should have meaningful info, e.g. 
     ```json
    {
      "status": "down",
      "services": {
        "redis": {
          "status": "ok"
        },
        "elasticsearch": {
          "status": "down",
          "error": "unable to reach http://elasticsearch.svc, Address unreachable"
        }
      }
    }
    ```

**Comment by hhiles** [comment]
@cbizon should this move to jira?

**Comment by cbizon** [comment]
@YaphetKG ?   Doesn't seem like a big pain point to me...

**Comment by YaphetKG** [comment]
@cbizon  agree, i think we have moved to using more stable third party charts , and cluster is also stable enough. In early days when using blackbalsam and mitchell, + simpler charts this was an issue.

**Comment by hhiles** [comment]
@cbizon @YaphetKG thank you both!
