### ISSUE TITLE
PhenX Parser

### ISSUE THREAD

**Issue by cschreep** [helxplatform/dug#162]
Implement a parser for the PhenX data

**Comment by YaphetKG** [comment]
https://www.phenxtoolkit.org/resources/download

**Comment by YaphetKG** [comment]
Data has changed since original implementation of  (https://github.com/helxplatform/heal-phenx-kgx-convertor) initial idea was to create a KGX file with this spec (https://docs.google.com/presentation/d/1f53IaENsZb3kEQEsKtalFxIikcKuDJfCFI-VS5Z47KU/edit#slide=id.gdf38eeabd9_0_0)
