### ISSUE TITLE
HEAL - Enable Ingest of NIDA metadata (NIDA Datashare Parser)

### ISSUE THREAD

**Issue by jcheadle-rti** [helxplatform/dug#163]
We want the ability to ingest NIDA Datashare metadata for the HEAL initiative.  NIDA is a big player within the HEAL initiative, and is the planned repository for around 300 studies, which is over half of the studies in the HEAL initiative.  They have well-documented metadata, but only a handful of studies contain machine-readable dictionaries (as .xlsx).  

I wrote a script to transform their data dictionaries to JSON blobs that can be ingested by Dug.  This issue tracks the progress from this metadata generation to making necessary code enhancements to allow for a (local) dug deployment with NIDA metadata, for demonstration purposes.

- [x] Add the NIDA deep dive to the slide deck. (John) 
https://docs.google.com/presentation/d/1mTGO7WW924Okb_TX2y8kJqcP_CJWJK4XTKzNy-fW524
- [x] Add study IDs to the NIDA JSON blobs where appropriate (John)
- [x] Work with Alex to do the merge for new Dug (On Wednesday) (John & @alexwaldrop)
- [ ] Figure out how to stand up a version of Dug that allows us to annotate NIDA data, and put it up in some version of Dug (even if that is local).  This will entail, probably, adding a plugin to ingest NIDA data. (@cschreep, @warrenstephens @alexwaldrop, John, etc.)
- [x] Then Talk with Matt about how the UI handles displaying variables that aren't necessarily attached to studies (@warrenstephens, Clark, @mbwatson, @alexwaldrop)

**Comment by jcheadle-rti** [comment]
zipped file of variable metadata blobs and study metadata attached
[outputs.zip](https://github.com/helxplatform/dug/files/6695393/outputs.zip)

**Comment by jcheadle-rti** [comment]
For context, here is a repo to store scripts that may generate Dug-ready data
https://ftp.ncbi.nlm.nih.gov/dbgap/studies/

**Comment by hhiles** [comment]
@jcheadle-rti is this still relevant?

>  Figure out how to stand up a version of Dug that allows us to annotate NIDA data, and put it up in some version of Dug (even if that is local). This will entail, probably, adding a plugin to ingest NIDA data. (@cschreep, @warrenstephens @alexwaldrop, John, etc.)

**Comment by jcheadle-rti** [comment]
@hhiles, this is complete and apologies for not tying this up.  @warrenstephens created a plugin long ago to transform NIDA data into the type of XML dictionary that Dug uses.
