### ISSUE TITLE
Ingest SPARC data 

### ISSUE THREAD

**Issue by cschreep** [helxplatform/dug#169]
Given sparc KGX in JSON format, ingest it into our ES index

@YaphetKG please work with Howard to flesh out detailed steps

**Comment by HowardLander** [comment]
@YaphetKG Can we close this?

**Comment by YaphetKG** [comment]
Hi @HowardLander , I think there are a couple of minor things left. 
* We would need to add the curation file location (heal/sparc/curation-export.json) to the metadata.yaml (https://github.com/helxplatform/roger/blob/main/dags/roger/metadata.yaml) . so  it would be downloaded and part of the next graph we built.

* next is to find some Tranql queries that would find links to these sparc items. We would extend [this list](https://github.com/helxplatform/roger/blob/c934704a37f5af02244a0211ee700727d63775b4/dags/roger/config.yaml#L51) with those queries. And that would I think let us have it ES index

**Comment by HowardLander** [comment]
Should we get together to do those things?  I have a docker that @cnbennett3 is building now in jenkins that does all the transformations, including the python code you wrote. I haven't written the jenkins task to run the docker yet.  I'm assuming we would want to to copy the final output json to heal/sparc/output-file name?

**Comment by YaphetKG** [comment]
I can start the graph building in k8s (my namespace) then we can get together for formulating some Tranql queries to add. Once your pipeline is ready we could replace the final kgx file.

**Comment by HowardLander** [comment]
This task is complete, so I am closing it!
