### ISSUE TITLE
give dug users context for missing search tiles

### ISSUE THREAD

**Issue by hhiles** [helxplatform/dug#213]
Some searches hide results that Dug deems irrelevant to the user. See screenshot for `HIV` where 13 results found, only 4 cards shown. 

@mbwatson update search results text to read something like `n results for "concept" (1 page) x results were removed because they do not contain sufficiently useful information.`

![image](https://user-images.githubusercontent.com/48485205/153043691-13642440-a762-4137-813b-d34664c513bf.png)

![image](https://user-images.githubusercontent.com/48485205/153043859-94ad5cb7-c0af-4e08-baae-fe584f55ef65.png)

**Comment by cbizon** [comment]
I noticed (I think) this issue yesterday when searching for "Alzheimer".  The search claims 21 results, but only 4 show.  However, the pagination still is based on the 21, so it thinks that there should be 2 pages. 

Is there a reason that we don't just say "4 results"?
