### ISSUE TITLE
Harmonization phase2

### ISSUE THREAD

**Issue by hhiles** [helxplatform/dug#218]
Incorporate CDE's, PhenX and LOINC harmonization into Dug

Acceptance Criteria:
* [ ] Ingest Variable cross-reference into knowledge graph from [phenx](https://www.phenxtoolkit.org/resources/download)
* [ ] Write queries that make associations between CDE's, PhenX and Loinc

**Comment by YaphetKG** [comment]
@hhiles , i don't think we have made much progress in this front. I think once we get CDE's properly presented, we can create KGX files for the PhenX + Loinc off of the downloads provided in the link above and use the same pattern we use for ingesting and presenting CDE's. 
(cc: @alexwaldrop ) Does this approach make sense?  i.e converting the [Protocol_cross_reference](https://www.phenxtoolkit.org/toolkit_content/documents/resources/Protocol_cross_reference.xlsx) file to KGX, and using CDE like approach to parse these nodes form the graph on crawling

**Comment by hhiles** [comment]
@YaphetKG is this work in jira?
