### ISSUE TITLE
Variable View

### ISSUE THREAD

**Issue by oihawkins** [helxplatform/dug#230]
Dates TBD by 5/24

For ~~MVP~~ dev testing
- [x] @hhiles set up meeting to discuss prod version of variable view - invite jeff, ginnie, mac, matt w
- [x] @gingin77 create image for @waTeim to pull
- [x] @hhiles and kira will play in this space for 1-2 weeks
- [x] @hhiles meet with @gingin77 and share screen to show any bugs/problems that are found during kira/hannah testing

For Beta with BDC @gingin77 
- [ ] Define Dug Score for users
- [ ] After zoom in, being able to select studies for further search - prioritize `variables` for "search within search" functionality
- [ ] Some kind of popup/help text to explain functionality of the push pins

Then
- [ ] @hhiles will work with kira to ID ~~HEAL~~ BDC users to beta test for 2-3 weeks - PREFERABLY JACKIE, Ben and Adrian would be helpful too
- [ ] @hhiles will set up a workshop meeting for 2-3 weeks from their access start date; discuss issues and what is liked

**Comment by hhiles** [comment]
- clicking variable in study drop down - launch new tab in background automatically?
- `Variables according to DUG Score` - change to `Variables according to Dug Score`
- also what is `Dug score`?
- when i highlighted `Variables according to DUG Score` it highlighted all the text in the popup window that hovers over the variables and i was unable to change cursor from the + symbol and interact with the webpage at all; had to delete URL back to just `https://helx-ghench.apps.renci.org/` and then it crashed
- studies seem like they should be listed by # of variables - are they instead listed by their 'Dug score'? can we explain this somewhere?

**Comment by gingin77** [comment]
Things I'm trying to reproduce:

- [ ] when i highlighted Variables according to DUG Score it highlighted all the text in the popup window...then it crashed << I'm not able to reproduce this. I was able to highlight the text, "Variables according to DUG Score" without any issues. I'm guessing the specifics of this problem are superficial to the same time lag effect I've experienced a few times when I've been doing lots of zooms & highlights in quick succession.

**Comment by gingin77** [comment]
Questions for Hannah:
- [ ] clicking variable in study drop down - launch new tab in background automatically?
> I do think they should open in a new tab and I can implement that change quickly. However, I'm not sure about "in background automatically" - maybe this is something Matt's done for other apps?
- [ ] also what is Dug score?
> _This is def something that the DUG search team needs to define for a user audience_ Programmatically, the DUG score is based on the Elastic Search Score with some extra weighting that is implemented in the variable search API endpoint function encoded in the DUG repo.
- [ ] studies seem like they should be listed by # of variables - are they instead listed by their 'Dug score'? can we explain this somewhere?
> Yes, the study order is based on the score of the variables they hold... This is because we're actually scoring the variables and then clustering them based on their study
> Yes, we can have some explanatory text somewhere - what is your preference? Again, this is probably a good things to coordinate with Matt

**Comment by gingin77** [comment]
Kira's comments
- threshold
- new tabs for each zoom view
- check boxes instead of push pins
- check boxes for the variables

**Comment by KCB13** [comment]
Some ideas of how the view changes as a user interacts with it: 
User goal: I want to combine 2+ datasets together, but I want to do so with the least amount of work possible. 
User flow: type in a concept that they are investigating (ex: heart attack, asthma, opioid-induced hyperalgesia) > search > select toggle view to see which variables scored the "highest" on the Dug score > zoom into the top ~10% of scores > opens a new tab with a histogram view of variables in the top 10% > I go through the table and select either specific variables (checkbox) or studies (checkbox) > have an option that allows me to compare data dictionary similarity (NEW FUNCTIONALITY) or allows me to figure out how easy it is to combine/harmonize these datasets (NEW FUNCTIONALITY) > OR I choose to keep these two studies selected and now I want to view ALL the variables associated with those two studies that are associated with the concept that I originally search for > new window of histogram viewer so I can see all the variables and their dug score (what are all the related variables that I should be looking at?)

**Comment by hhiles** [comment]
![image](https://user-images.githubusercontent.com/48485205/173848798-b4d038b8-998d-4e43-a0cb-caca45fb4279.png)

- functionality where user can click on bar that has variable that they are interested in

**Comment by hhiles** [comment]
need to be able to define `Variables according to DUG Score` on page for users

**Comment by frostyfan109** [comment]
Extra histogram options would be awesome to have in the future. For reference, something like matplotlib allows the user to go reset zoom, go back/forward in your zooms, save the figure, and other adjustments.

<img width="639" alt="image" src="https://user-images.githubusercontent.com/31631417/184426934-8b184fab-a898-4ab7-9748-5258c1ae9c7d.png">

**Comment by gingin77** [comment]
@hhiles, Griffin and I are reviewing the notes on this issue ticket.
- [ ] Do you remember what you meant by  "search within search" functionality? 
- [ ] Do you have a definition for DUG Score - if not, would Guarav or Yaphet? Here's a link to the boosting on the API endpoint, [search.py#L307](https://github.com/helxplatform/dug/blob/de738e0a24aafc3306e318f7675d075a5a2e4b73/src/dug/core/search.py#L307)
- [ ] Some kind of popup/help text to explain functionality of the push pins >>> "Select <pin icon> to highlight variables from this study"

**Comment by hhiles** [comment]
@gingin77 

1. "search within search" was the ability for users to narrow their search. Eg, I could run a search for `diabetes` and then search within those results again either with a second search, with adding filters, removing results, etc... some kind of functionality for filtering. 
2. John Cheadle was the one we were depending on for that in the past; @gaurav or @YaphetKG would be my second guess. 
3. I like that description for the push pins!

**Comment by YaphetKG** [comment]
Hi @gingin77 , i believe the dug scoring currently relies on Elastic Search scoring. [Here is an article](https://www.compose.com/articles/how-scoring-works-in-elasticsearch/)  explaining how that works,
