### ISSUE TITLE
How to handle "disease" as text in a search?

### ISSUE THREAD

**Issue by cbizon** [helxplatform/dug#239]
Searching for something like "heart disease" returns a lot of good hits.  But it also returns things like "brain disease" and "polydactyly (disease)".

My suspicion is that the text "disease" is producing these matches.   Is there a way to down-weight those results?   Maybe disease should be removed from names?  But seems like you need it in there to get heart disease to match heart disease...

**Comment by hhiles** [comment]
@cbizon should this move to jira?

**Comment by cbizon** [comment]
Yes
