### ISSUE TITLE
ingest the Ousmane dataset

### ISSUE THREAD

**Issue by krobasky** [helxplatform/dug#255]
- [ ] @alexwaldrop please confirm that you have the dictionary that we will be using for this; if not we need to access it somewhow
- [ ] @cmball1 to review what the needs are for ingesting the dictionary

**Comment by krobasky** [comment]
I don't have permission to assign a label, otherwise I would tag this with "HEAL" at Chris Bizon's request.

**Comment by cbizon** [comment]
This will be one of the dictionaries that Ousmane has uncovered and we will parse it without worrying too much about the long term pipeline.  The idea here is to have a dictionary indexed in heal for socialization purposes.

**Comment by hhiles** [comment]
- @alexwaldrop please confirm that you have the dictionary that we will be using for this; if not we need to access it somewhow
- @cmball1 to review what the needs are for ingesting the dictionary

**Comment by YaphetKG** [comment]
Hi @cmball1, hope all is well, today's scrum @gaurav  mentioned that Ousmane might some datasets that we could ingest,  looking to sync up on the next steps for ingesting those datasets  into dug. 
(cc: @cbizon )

**Comment by cmball1** [comment]
[copy_StanfordSPRINT_DataDictionary_2020-12-16.csv](https://github.com/helxplatform/dug/files/9497639/copy_StanfordSPRINT_DataDictionary_2020-12-16.csv)
@YaphetKG Here is one of the data dictionaries we have. I think there is another one, I need to find to attach here.

**Comment by YaphetKG** [comment]
We have SPRINT and BACPAC in the works and are being followed in JIRA (https://renci.atlassian.net/browse/DUG-20)
