### ISSUE TITLE
Define ingestion process and implement v1

### ISSUE THREAD

**Issue by krobasky** [helxplatform/dug#256]

**Comment by krobasky** [comment]
I don't have permission to assign a label, otherwise I would tag this with "HEAL" at Chris Bizon's request.

**Comment by hhiles** [comment]
@cbizon is this ticket one you want recreated in jira?

**Comment by cbizon** [comment]
I think we have this captured

**Comment by hhiles** [comment]
Excellent. I will mark it as transferred then. Thanks!
