### ISSUE TITLE
Improve NER on Dug

### ISSUE THREAD

**Issue by hhiles** [helxplatform/dug#261]
@gaurav to create backlog of tickets representing the NER work

Current list:
- [ ] https://github.com/RENCI-NER/benchmarks/issues/2

**Comment by gaurav** [comment]
I've created a project tracking all RENCI NER Working Group activities at https://github.com/orgs/RENCI-NER/projects/2/views/1. I think HEAL's need is fully summarized by the following issue:
- [ ] https://github.com/RENCI-NER/benchmarks/issues/2

If there are additional issues that become relevant here, I'll add them to this list as well.

**Comment by gaurav** [comment]
Superceded by [DUG-2](https://renci.atlassian.net/browse/DUG-2) in the RENCI Jira instance. Closing here.
