### ISSUE TITLE
Allow for alternate annotator classes

### ISSUE THREAD

**Issue by braswent** [helxplatform/dug#329]
Allow Dug Annotator to be defined by the user by following the same protocols used for the Parser on Annotators.

The following functionality is expected:

- Pass the annotator Class name as a string to a `Pluggy` hookspec function
- Define the existing Annotator class in the same way that the Parser class is defined in `core/parsers/__init__.py`
- **@YaphetKG should we do this too?** Connect the Annotator class selection into the Roger repo in `dug_helpers/dug_utils.py` and `metadata.yaml`

**Comment by YaphetKG** [comment]
Yeah but i think we can do that after we wrap this up and integrate it in a later version of roger maybe?
